// Auto-generated by: supabase gen types typescript --linked
// Do not edit manually — re-run the command to regenerate.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.1"
  }
  graphql_public: {
    Tables: { [_ in never]: never }
    Views:  { [_ in never]: never }
    Functions: {
      graphql: {
        Args: { extensions?: Json; operationName?: string; query?: string; variables?: Json }
        Returns: Json
      }
    }
    Enums: { [_ in never]: never }
    CompositeTypes: { [_ in never]: never }
  }
  public: {
    Tables: {
      api_keys: {
        Row: {
          created_at:   string | null
          created_by:   string | null
          id:           string
          key_hash:     string
          key_prefix:   string
          label:        string | null
          last_used_at: string | null
          org_id:       string | null
          project_id:   string | null
        }
        Insert: {
          created_at?:   string | null
          created_by?:   string | null
          id?:           string
          key_hash:      string
          key_prefix:    string
          label?:        string | null
          last_used_at?: string | null
          org_id?:       string | null
          project_id?:   string | null
        }
        Update: {
          created_at?:   string | null
          created_by?:   string | null
          id?:           string
          key_hash?:     string
          key_prefix?:   string
          label?:        string | null
          last_used_at?: string | null
          org_id?:       string | null
          project_id?:   string | null
        }
        Relationships: [
          { foreignKeyName: "api_keys_org_id_fkey";    columns: ["org_id"];    isOneToOne: false; referencedRelation: "organisations"; referencedColumns: ["id"] },
          { foreignKeyName: "api_keys_project_id_fkey"; columns: ["project_id"]; isOneToOne: false; referencedRelation: "projects";      referencedColumns: ["id"] },
        ]
      }
      audit_log: {
        Row: {
          action:     string
          created_at: string | null
          id:         string
          metadata:   Json | null
          org_id:     string | null
          user_id:    string | null
        }
        Insert: {
          action:      string
          created_at?: string | null
          id?:         string
          metadata?:   Json | null
          org_id?:     string | null
          user_id?:    string | null
        }
        Update: {
          action?:     string
          created_at?: string | null
          id?:         string
          metadata?:   Json | null
          org_id?:     string | null
          user_id?:    string | null
        }
        Relationships: [
          { foreignKeyName: "audit_log_org_id_fkey"; columns: ["org_id"]; isOneToOne: false; referencedRelation: "organisations"; referencedColumns: ["id"] },
        ]
      }
      invitations: {
        Row: {
          accepted_at: string | null
          created_at:  string | null
          email:       string
          expires_at:  string | null
          id:          string
          invited_by:  string | null
          org_id:      string | null
          role:        string | null
          token:       string
        }
        Insert: {
          accepted_at?: string | null
          created_at?:  string | null
          email:        string
          expires_at?:  string | null
          id?:          string
          invited_by?:  string | null
          org_id?:      string | null
          role?:        string | null
          token:        string
        }
        Update: {
          accepted_at?: string | null
          created_at?:  string | null
          email?:       string
          expires_at?:  string | null
          id?:          string
          invited_by?:  string | null
          org_id?:      string | null
          role?:        string | null
          token?:       string
        }
        Relationships: [
          { foreignKeyName: "invitations_org_id_fkey"; columns: ["org_id"]; isOneToOne: false; referencedRelation: "organisations"; referencedColumns: ["id"] },
        ]
      }
      org_members: {
        Row: {
          invited_by: string | null
          joined_at:  string | null
          org_id:     string
          role:       string | null
          user_id:    string
        }
        Insert: {
          invited_by?: string | null
          joined_at?:  string | null
          org_id:      string
          role?:       string | null
          user_id:     string
        }
        Update: {
          invited_by?: string | null
          joined_at?:  string | null
          org_id?:     string
          role?:       string | null
          user_id?:    string
        }
        Relationships: [
          { foreignKeyName: "org_members_org_id_fkey"; columns: ["org_id"]; isOneToOne: false; referencedRelation: "organisations"; referencedColumns: ["id"] },
        ]
      }
      organisations: {
        Row: {
          created_at: string | null
          id:         string
          name:       string
          slug:       string
        }
        Insert: {
          created_at?: string | null
          id?:         string
          name:        string
          slug:        string
        }
        Update: {
          created_at?: string | null
          id?:         string
          name?:       string
          slug?:       string
        }
        Relationships: []
      }
      projects: {
        Row: {
          created_at:  string | null
          description: string | null
          id:          string
          name:        string
          org_id:      string
          slug:        string
        }
        Insert: {
          created_at?:  string | null
          description?: string | null
          id?:          string
          name:         string
          org_id:       string
          slug:         string
        }
        Update: {
          created_at?:  string | null
          description?: string | null
          id?:          string
          name?:        string
          org_id?:      string
          slug?:        string
        }
        Relationships: [
          { foreignKeyName: "projects_org_id_fkey"; columns: ["org_id"]; isOneToOne: false; referencedRelation: "organisations"; referencedColumns: ["id"] },
        ]
      }
      runs: {
        Row: {
          branch:         string | null
          commit_message: string | null
          commit_sha:     string | null
          created_at:     string | null
          duration_ms:    number | null
          failed:         number | null
          framework:      string | null
          id:             string
          metadata:       Json | null
          org_id:         string | null
          passed:         number | null
          project_id:     string | null
          skipped:        number | null
          total:          number | null
          triggered_by:   string | null
        }
        Insert: {
          branch?:         string | null
          commit_message?: string | null
          commit_sha?:     string | null
          created_at?:     string | null
          duration_ms?:    number | null
          failed?:         number | null
          framework?:      string | null
          id?:             string
          metadata?:       Json | null
          org_id?:         string | null
          passed?:         number | null
          project_id?:     string | null
          skipped?:        number | null
          total?:          number | null
          triggered_by?:   string | null
        }
        Update: {
          branch?:         string | null
          commit_message?: string | null
          commit_sha?:     string | null
          created_at?:     string | null
          duration_ms?:    number | null
          failed?:         number | null
          framework?:      string | null
          id?:             string
          metadata?:       Json | null
          org_id?:         string | null
          passed?:         number | null
          project_id?:     string | null
          skipped?:        number | null
          total?:          number | null
          triggered_by?:   string | null
        }
        Relationships: [
          { foreignKeyName: "runs_org_id_fkey";    columns: ["org_id"];    isOneToOne: false; referencedRelation: "organisations"; referencedColumns: ["id"] },
          { foreignKeyName: "runs_project_id_fkey"; columns: ["project_id"]; isOneToOne: false; referencedRelation: "projects";      referencedColumns: ["id"] },
        ]
      }
      suites: {
        Row: {
          duration_ms: number | null
          failed:      number | null
          id:          string
          name:        string
          org_id:      string | null
          passed:      number | null
          run_id:      string | null
          skipped:     number | null
          total:       number | null
        }
        Insert: {
          duration_ms?: number | null
          failed?:      number | null
          id?:          string
          name:         string
          org_id?:      string | null
          passed?:      number | null
          run_id?:      string | null
          skipped?:     number | null
          total?:       number | null
        }
        Update: {
          duration_ms?: number | null
          failed?:      number | null
          id?:          string
          name?:        string
          org_id?:      string | null
          passed?:      number | null
          run_id?:      string | null
          skipped?:     number | null
          total?:       number | null
        }
        Relationships: [
          { foreignKeyName: "suites_org_id_fkey"; columns: ["org_id"]; isOneToOne: false; referencedRelation: "organisations"; referencedColumns: ["id"] },
          { foreignKeyName: "suites_run_id_fkey"; columns: ["run_id"]; isOneToOne: false; referencedRelation: "runs";           referencedColumns: ["id"] },
        ]
      }
      test_results: {
        Row: {
          duration_ms:   number | null
          error_message: string | null
          error_stack:   string | null
          full_name:     string | null
          id:            string
          name:          string
          org_id:        string | null
          retry_count:   number | null
          run_id:        string | null
          state:         string | null
          suite_id:      string | null
        }
        Insert: {
          duration_ms?:   number | null
          error_message?: string | null
          error_stack?:   string | null
          full_name?:     string | null
          id?:            string
          name:           string
          org_id?:        string | null
          retry_count?:   number | null
          run_id?:        string | null
          state?:         string | null
          suite_id?:      string | null
        }
        Update: {
          duration_ms?:   number | null
          error_message?: string | null
          error_stack?:   string | null
          full_name?:     string | null
          id?:            string
          name?:          string
          org_id?:        string | null
          retry_count?:   number | null
          run_id?:        string | null
          state?:         string | null
          suite_id?:      string | null
        }
        Relationships: [
          { foreignKeyName: "test_results_org_id_fkey";   columns: ["org_id"];   isOneToOne: false; referencedRelation: "organisations"; referencedColumns: ["id"] },
          { foreignKeyName: "test_results_run_id_fkey";   columns: ["run_id"];   isOneToOne: false; referencedRelation: "runs";           referencedColumns: ["id"] },
          { foreignKeyName: "test_results_suite_id_fkey"; columns: ["suite_id"]; isOneToOne: false; referencedRelation: "suites";         referencedColumns: ["id"] },
        ]
      }
    }
    Views: { [_ in never]: never }
    Functions: {
      create_org: {
        Args:    { p_name: string; p_slug: string }
        Returns: string  // returns the new org UUID
      }
      get_user_orgs: {
        Args:    { p_user_id: string }
        Returns: { created_at: string; id: string; name: string; role: string; slug: string }[]
      }
      validate_api_key: {
        Args:    { p_key_hash: string }
        Returns: { org_id: string; project_id: string }[]
      }
    }
    Enums: { [_ in never]: never }
    CompositeTypes: { [_ in never]: never }
  }
}

// ---------------------------------------------------------------------------
// Convenience row types (derived from the generated Database type above)
// ---------------------------------------------------------------------------
export type Organisation = Database['public']['Tables']['organisations']['Row'];
export type OrgMember    = Database['public']['Tables']['org_members']['Row'];
export type Project      = Database['public']['Tables']['projects']['Row'];
export type ApiKey       = Database['public']['Tables']['api_keys']['Row'];
export type Run          = Database['public']['Tables']['runs']['Row'];
export type Suite        = Database['public']['Tables']['suites']['Row'];
export type TestResult   = Database['public']['Tables']['test_results']['Row'];
export type AuditLog     = Database['public']['Tables']['audit_log']['Row'];
export type Invitation   = Database['public']['Tables']['invitations']['Row'];

export interface OrgWithRole extends Organisation {
  role: string;
}

// Narrowed literal types used in UI logic
export type Role          = 'owner' | 'admin' | 'member' | 'viewer';
export type InvitationRole = 'admin' | 'member' | 'viewer';
export type TestState     = 'passed' | 'failed' | 'skipped' | 'pending';
export type TriggeredBy   = 'ci' | 'manual' | 'api';
